In [1]:
from census import Census
import gmaps
import numpy as np
import pandas as pd
import requests
import time
from scipy.stats import linregress
from matplotlib import pyplot as plt

In [12]:
url = "https://data.cdc.gov/resource/9mfq-cb36.json"  

response = requests.get(url).json()
Covid_data = pd.DataFrame(response) 
Covid_data

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
0,2020-05-04T00:00:00.000,KY,5245,5245.0,0,115.0,0,261,261.0,0,8.0,0,2020-05-05T17:25:08.000,Agree,Agree
1,2020-12-08T00:00:00.000,OK,205999,171497.0,34502,0.0,0,1752,1680.0,72,0.0,0,2020-12-09T14:45:40.234,Agree,Agree
2,2020-08-21T00:00:00.000,MD,103523,NaN,NaN,624.0,0,3685,3546.0,139,11.0,1,2020-08-22T14:21:09.869,N/A,Agree
3,2020-03-05T00:00:00.000,GA,2,NaN,NaN,-5.0,NaN,0,NaN,NaN,0.0,NaN,2020-03-26T16:22:39.452,Agree,Agree
4,2020-02-08T00:00:00.000,WA,1,NaN,NaN,0.0,NaN,0,NaN,NaN,0.0,NaN,2020-03-26T16:22:39.452,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020-02-05T00:00:00.000,KY,0,NaN,NaN,0.0,NaN,0,NaN,NaN,0.0,NaN,2020-03-26T16:22:39.452,Agree,Agree
996,2020-03-04T00:00:00.000,NV,0,NaN,NaN,0.0,NaN,0,NaN,NaN,0.0,NaN,2020-03-26T16:22:39.452,NaN,NaN
997,2020-05-22T00:00:00.000,GA,39387,39365.0,22,1031.0,0,1808,1808.0,0,50.0,0,2020-05-23T13:58:16.000,Agree,Agree
998,2020-08-27T00:00:00.000,AL,121023,112794.0,8229,1769.0,1101,2076,1990.0,86,31.0,6,2020-08-28T13:43:49.392,Agree,Agree
999,2020-08-04T00:00:00.000,ND,7057,7057.0,0,124.0,0,108,NaN,NaN,1.0,0,2020-08-05T14:13:18.333,Agree,Not agree

In [13]:
KY = Covid_data.loc[Covid_data["state"] == "KY"]

In [14]:
KY

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
0,2020-05-04T00:00:00.000,KY,5245,5245.0,0,115.0,0,261,261.0,0,8.0,0,2020-05-05T17:25:08.000,Agree,Agree
78,2020-05-22T00:00:00.000,KY,8426,8305.0,121,140.0,10,391,390.0,1,5.0,0,2020-05-23T17:58:16.000,Agree,Agree
80,2020-03-19T00:00:00.000,KY,43,NaN,NaN,8.0,NaN,2,NaN,NaN,1.0,NaN,2020-03-26T16:22:39.452,Agree,Agree
249,2020-07-11T00:00:00.000,KY,19121,18307.0,814,451.0,34,622,618.0,4,2.0,0,2020-07-12T15:13:57.799,Agree,Agree
373,2020-06-11T00:00:00.000,KY,11945,11637.0,308,62.0,1,493,491.0,2,9.0,0,2020-06-12T14:17:59.811,Agree,Agree
405,2020-11-20T00:00:00.000,KY,152206,125825.0,26381,3816.0,672,1762,1720.0,42,20.0,1,2020-11-21T14:59:41.222,Agree,Agree
408,2020-08-05T00:00:00.000,KY,32741,30712.0,2029,544.0,70,752,748.0,4,1.0,0,2020-08-06T14:12:27.571,Agree,Agree
459,2020-04-27T00:00:00.000,KY,4146,4146.0,0,72.0,0,213,213.0,0,5.0,0,2020-05-25T15:38:40.000,Agree,Agree
537,2020-10-11T00:00:00.000,KY,80292,69138.0,11154,847.0,151,1252,1239.0,13,3.0,0,2020-10-12T14:07:08.478,Agree,Agree
565,2020-07-28T00:00:00.000,KY,28126,26656.0,1470,525.0,78,719,715.0,4,10.0,0,2020-07-29T14:34:46.946,Agree,Agree
573,2021-01-17T00:00:00.000,KY,326675,259967.0,66708,2350.0,377,3127,2884.0,243,34.0,8,2021-01-18T14:39:32.141,Agree,Agree
661,2020-05-13T00:00:00.000,KY,7080,7080.0,0,227.0,0,326,326.0,0,5.0,0,2020-05-14T17:25:44.000,Agree,Agree
678,2020-06-21T00:00:00.000,KY,13750,13369.0,381,120.0,4,526,523.0,3,2.0,0,2020-06-22T15:24:02.542,Agree,Agree
685,2020-04-22T00:00:00.000,KY,3373,3373.0,0,181.0,0,185,185.0,0,14.0,0,2020-04-22T16:22:39.452,Agree,Agree
793,2020-09-24T00:00:00.000,KY,64158,56608.0,7550,641.0,187,1137,1128.0,9,13.0,0,2020-09-25T13:54:10.196,Agree,Agree
801,2020-03-22T00:00:00.000,KY,103,NaN,NaN,16.0,NaN,3,NaN,NaN,0.0,NaN,2020-03-26T16:22:39.452,Agree,Agree
840,2020-05-12T00:00:00.000,KY,6853,6853.0,0,176.0,0,321,321.0,0,10.0,0,2020-05-13T15:26:08.000,Agree,Agree
862,2020-09-08T00:00:00.000,KY,53319,48141.0,5178,255.0,70,997,988.0,9,1.0,0,2020-09-09T13:47:50.836,Agree,Agree
894,2020-12-30T00:00:00.000,KY,265262,213256.0,52006,3770.0,1062,2623,2446.0,177,29.0,7,2020-12-31T14:55:07.623,Agree,Agree
953,2020-06-22T00:00:00.000,KY,13839,13449.0,390,89.0,9,526,522.0,4,0.0,1,2020-06-23T14:28:19.177,Agree,Agree
985,2020-11-08T00:00:00.000,KY,120838,100791.0,20047,1177.0,201,1565,1538.0,27,4.0,0,2020-11-09T14:38:54.660,Agree,Agree
995,2020-02-05T00:00:00.000,KY,0,NaN,NaN,0.0,NaN,0,NaN,NaN,0.0,NaN,2020-03-26T16:22:39.452,Agree,Agree